Add singleton pattern source files
desarrolladorSLP/Design-Patterns-Java pull request #29
Opened 2017-03-29 04:10 UTC by EnriqueGuardiola

Singleton pattern clases

2017-03-29 17:52 UTC, iuresti requested changes
It is important to add Readme.md file with the explanation of your pattern.

2017-03-29 17:52 UTC, iuresti commented on Singleton/src/main/java/devslp/designpatterns/singleton/LoggerTest.java
> +class Logger {
Please use one class per file

2017-03-29 17:52 UTC, iuresti commented on Singleton/src/main/java/devslp/designpatterns/singleton/LoggerTest.java
> + * @author Enrique Guardiola
I'd recommend to remove the author from the source code files: http://stackoverflow.com/questions/17269843/javadoc-author-tag-good-practices

2017-03-29 19:00 UTC, iuresti requested changes
Remember to remove the author in every single file. We have git to keep track of the authors.

2017-03-30 01:07 UTC, eloyhz commented
¿@iuresti que pasa si dejo un comentario sobre los archivos modificados? ¿deberían aparecer en esta conversación las preguntas?

2017-03-30 01:25 UTC, iuresti commented
@eloyhz yo creo que si... Pero probemos

2017-04-18 01:28 UTC, iuresti approved these changes

2017-04-18 01:30 UTC, merged